---
name: Backport Assistant Runner

on:
  pull_request:
    types:
      - labeled
      - closed

jobs:
  backport:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    container: hashicorpdev/backport-assistant:0.3.6
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run backport assistant
        run: |
          backport-assistant backport
          env:
          BACKPORT_LABEL_REGEXP: "backport/(?P<target>\\d+\\.\\d+\\.[+\\w])"
          BACKPORT_TARGET_TEMPLATE: "releases/{{.target}}"
          GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}

  backport-ent:
      if: github.event.pull_request.merged && contains(join(github.event.pull_request.labels.*.name), 'backport/ent')
      runs-on: ubuntu-latest
      steps:
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v3
          with:
            token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
            repository: HashiCorp-RelEng-Dev/bpa-test-ent
            event-type: ent-backport
            client-payload: ${{ toJson(github.event) }}

