name: Backport Validate

on:
  pull_request:
    types: [ labeled ]

jobs:
  test-validate:
    # if: github.event.pull_request.state == open
    container: hashicorpdev/backport-assistant:claire-dev
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v2
    - name: Check Label Duplication
      run: |
        echo ${{ github.event.label.name }}
        export LABELS="$(echo jq --raw-output 'map(.name) | join(",")') | '${{ ToJSON( github.event.pull_request.labels ) }}'"
        echo ${LABELS}
        export PR_NUMBER=${{ github.event.pull_request.number }}
        export GITHUB_TOKEN=${{ secrets.ELEVATED_GITHUB_TOKEN }}
        backport-assistant validate \
            --owner hashicorp-releng-dev --repo bpa-test-oss
   
