name: Backport Validate
run-name: Validate backports for versions ${{ inputs.versions }} since ${{ inputs.begin-date }}
on:
  workflow_dispatch:
    inputs:
      versions:
        description: "A comma seperated string of the x.y versions representing the backport labels to check. Example: 1.13,1.14,1.15"
        required: true
        type: string
      begin-date:
        description: Begin Date to check for PRs being merged.  In the format of YYYY-MM-DD.
        required: true
        type: string

env:
  GOPRIVATE: github.com/hashicorp # Required for private/internal backport-checker repo
  GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}

jobs:
  validate-backports-oss:
    container: hashicorpdev/backport-assistant:claire-dev
    runs-on: [ 'ubuntu-latest' ]
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: 'go.mod'
      # NOTE: This step is specifically needed for ENT. It allows us to access the required private HashiCorp repos.
      - name: Setup Git
        run: git config --global url."https://${{ secrets.ELEVATED_GITHUB_TOKEN}}:@github.com".insteadOf "https://github.com"
      - name: backport validate
        run: |
          go run github.com/hashicorp/backport-checker validate \
            --owner hashicorp --repo consul --sync-repo consul-enterprise --versions ${{ inputs.versions }} \
            --begin-date ${{ inputs.begin-date }}

  validate-backports-enterprise:
    container: hashicorpdev/backport-assistant:claire-dev
    runs-on: [ 'ubuntu-latest' ]
    # needs to run serially because github search api limits to 30 req/minute.
    # running in parallel will push it over the limit.
    needs:
      - validate-backports-oss
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: 'go.mod'
      # NOTE: This step is specifically needed for ENT. It allows us to access the required private HashiCorp repos.
      - name: Setup Git
        run: git config --global url."https://${{ secrets.ELEVATED_GITHUB_TOKEN }}:@github.com".insteadOf "https://github.com"
      - name: backport validate
        run: |
          go run github.com/hashicorp/backport-checker validate \
            --owner hashicorp --repo consul-enterprise --versions ${{ inputs.versions }} \
            --begin-date ${{ inputs.begin-date }}
