---
name: Backport Assistant Runner 
run-name: "BPA Run :: ${{ github.event.pull_request.title }}: ${{ github.head_ref }}"
on:
  workflow_dispatch:
    inputs:
      versions:
        description: "A comma seperated string of the x.y versions representing the backport labels to check. Example: 1.13,1.14,1.15"
        required: true
        type: string
      begin-date:
        description: Begin Date to check for PRs being merged.  In the format of YYYY-MM-DD.
        required: true
        type: string
  pull_request:
    types:
      - labeled
      - closed

jobs:
  backport:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    container: hashicorpdev/backport-assistant:0.4.5-dev
    steps:
      - name: run backport assistant
        run: |
          backport-assistant backport
        env:
          # Nomad, Vault, and Boundary label + template conventions
          # BACKPORT_LABEL_REGEXP: "backport/(?P<target>\\d+\\.\\d+\\.[+\\w]+)"
          # BACKPORT_TARGET_TEMPLATE: "release/{{.target}}"
          
          # Consul label + template conventions
          BACKPORT_LABEL_REGEXP: "backport/(?P<target>\\d+\\.\\d+)"
          BACKPORT_TARGET_TEMPLATE: "release/{{.target}}.x"
          # GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
          ENABLE_VERSION_MANIFESTS: true
      - name: print event
        env:
            EVENT: ${{ toJson(github.event) }}
        run: |
          echo "$EVENT"

  backport-ent:
      if: github.event.pull_request.merged && contains(join(github.event.pull_request.labels.*.name), 'backport/ent')
      runs-on: ubuntu-latest
      steps:
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
          with:
            token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
            repository: HashiCorp-RelEng-Dev/bpa-test-enterprise
            event-type: ent-backport
            client-payload: ${{ toJson(github.event) }}
