name: Backport Validate

on:
  pull_request:
    types: [ labeled ]

jobs:
  test-validate:
    # if: github.event.pull_request.state == open
    container: hashicorpdev/backport-assistant:claire-dev
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v4
    - name: Check Label Duplication
      env: 
        GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
        LABELS: "backport/1.16.x,backport/ent/1.16.x+ent"
        # LABELS: $(echo ${{ ToJSON( github.event.pull_request.labels ) }} | jq --raw-output 'map(.name) | join(",")')
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        backport-assistant validate --owner hashicorp-releng-dev --repo bpa-test-oss
   
