name: Backport Commenter
run-name: Validate backports for versions ${{ inputs.versions }} since ${{ inputs.begin-date }} and notify PRs owners
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
    inputs:
        versions:
            description: "A comma seperated string of the x.y versions representing the backport labels to check. Example: 1.13,1.14,1.15"
            required: true
            type: string
        begin-date:
            description: Begin Date to check for PRs being merged.  In the format of YYYY-MM-DD.
            required: true
            type: string

env:
  GOPRIVATE: github.com/hashicorp # Required for private/internal backport-checker repo
  GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}

jobs:
  validate-backports-oss:
    container: hashicorpdev/backport-assistant:claire-dev
    runs-on: [ 'ubuntu-latest' ]
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: 'go.mod'
      # NOTE: This step is specifically needed for ENT. It allows us to access the required private HashiCorp repos.
      - name: Setup Git
        run: git config --global url."https://${{ secrets.ELEVATED_GITHUB_TOKEN }}:@github.com".insteadOf "https://github.com"
      - name: backport commenter
        env:
          BEGIN_DATE: "${{ vars.BEGIN_DATE }}" 
          VERSIONS: "${{ vars.VERSIONS }}"
        run: |
          backport-assistant validate \
            --owner hashicorp-releng-dev --repo bpa-test-oss --sync-repo bpa-test-enterprise --versions "${VERSIONS}" \
            --begin-date "${BEGIN_DATE}" --add-comment
