---
name: Backport Assistant Runner

on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    container: hashicorpdev/backport-assistant:0.3.5
    steps:
      - name: print event
        env:
          EVENT: ${{ toJson(github.event) }}
        run: |
          echo "$EVENT"
      - name: Run Backport Assistant
        run: |
          backport-assistant backport
        env:
          BACKPORT_LABEL_REGEXP: "(?P<target>\\d+\\.\\d+\\.[+\\w]+)-backport"
          BACKPORT_TARGET_TEMPLATE: "releases/{{.target}}"
          GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
