---
name: Backport Assistant Runner

on:
  pull_request:
    types:
      - labeled
      - closed

jobs:
  backport:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    container: hashicorpdev/backport-assistant:claire-dev
    steps:
      - name: run backport assistant
        run: |
          backport-assistant backport -merge-method=squash
        env:
          BACKPORT_LABEL_REGEXP: "backport/(?P<target>\\d+\\.\\d+\\.[+\\w]+)"
          BACKPORT_TARGET_TEMPLATE: "release/{{.target}}"
          GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
          ENABLE_VERSION_MANIFESTS: true

  backport-ent:
      if: github.event.pull_request.merged && contains(join(github.event.pull_request.labels.*.name), 'backport/ent')
      runs-on: ubuntu-latest
      steps:
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
          with:
            token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
            repository: HashiCorp-RelEng-Dev/bpa-test-enterprise
            event-type: ent-backport
            client-payload: ${{ toJson(github.event) }}

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: backport validate
        run: |
          backport-assistant validate --owner hashicorp-releng-dev --repo bpa-test-oss --sync-repo bpa-test-enterprise --versions 1.15, 1.16 --begin-date 2024-06-20
