name: test

on:
  push:
  workflow_dispatch:

jobs:
  check-for-updates:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - run: echo "I'm just doing a test"
